zap:
  level: info
  encoding: json
  outputPaths:
    - stdout
    - /tmp/logs
  disableCaller: false
  encoderConfig:
    messageKey: message
    levelKey: level
    levelEncoder: lowercase
    timeKey: ts
    timeEncoder: ISO8601
    callerKey: caller
    callerEncoder: short
